# carrega as bibliotecas
pacman::p_load(ade4, car, caret, corrplot, data.table, dplyr, e1071, forcats, funModeling, ggplot2, mlbench, mltools, randomForest, rattle, tidyverse, lubridate)

# base de dados
acessoInformacao <- read.csv2('http://dados.recife.pe.gov.br/dataset/c7f0f953-d982-4ee8-920c-e174cc54f9cc/resource/28d07b08-a119-4b19-bfc9-0ce79e32bb29/download/pedidosinformacao20202.csv', encoding="UTF-8")

# selecionando colunas relevantes
acessoInformacao <- acessoInformacao %>%
  select(c(3,4,5,6,10,11,12,26:29,31), )

# transformando variavel cidade
acessoInformacao$cidade_solicitante <- ifelse(acessoInformacao$cidade_solicitante == 'Recife', 'Recife', "Outra")

# calculando o numero de dias
acessoInformacao <- acessoInformacao %>%
  mutate(dias = difftime(data_resposta, data_pedido, units = "days"))

acessoInformacao$dias <- as.numeric(acessoInformacao$dias)

# verificar se as colunas sao diferentes
acessoInformacao <- acessoInformacao %>%
  mutate(comparison = if_else(
    as.character(orgao_solicitacao) == as.character(orgao_resposta), "igual", "diferente"
  ))

# Filtrando outliers
acessoInformacao <- acessoInformacao[c(1:803, 806:824), ]

# Discretizando
table(acessoInformacao$profissao_solicitante)

acessoInformacao_1 <- acm.disjonctif(as.data.frame(acessoInformacao$orgao_solicitacao))
names(acessoInformacao_1) <- c('ASSESSORIA.ESPECIAL', 'AUTARQUIA.DE.MANUTENCAO.E.LIMPEZA.URBANA', 'AUTARQUIA.DE.SERVICOS.URBANOS.DO.RECIFE', 'AUTARQUIA.DE.TRANSITO.E.TRANSPORTE.URBANO.DO.RECIFE', 'AUTARQUIA.DE.URBANIZACAO.DO.RECIFE', 'AUTARQUIA.MUNICIPAL.DE.PREVID.E.ASSISTÊNCIA.A.SAUDE.SERVIDORES', 'CONTROLADORIA.GERAL.DO.MUNICIPIO', 'EMPRESA.MUNICIPAL.DE.INFORMATICA', 'FUNDACAO.DE.CULTURA.DA.CIDADE.DO.RECIFE', 'GABINETE.DE.IMPRENSA', 'GABINETE.DE.PROJETOS.ESPECIAIS', 'GABINETE.DE.REPRESENTACAO.EM.BRASILIA.E.RELACOES.INTERNACIONAIS', 'GABINETE.DO.PREFEITO', 'PROCURADORIA.GERAL.DO.MUNICIPIO', 'SEC.DE.DESENV.SOCIAL.JUVENTUDE.POLIT.SOBRE.DROGA.E.DIR.HUMANOS', 'SECRETARIA.DE.ADMINISTRAÇÃO.E.GESTAO.DE.PESSOAS', 'SECRETARIA.DE.CULTURA', 'SECRETARIA.DE.DESENV.ECONÔMICO.CIÊNCIA.TECNOLOGIA.E.INOVAÇÃO', 'SECRETARIA.DE.EDUCACAO', 'SECRETARIA.DE.FINANCAS', 'SECRETARIA.DE.GOVERNO.E.PARTICIPACAO.SOCIAL', 'SECRETARIA.DE.HABITACAO', 'SECRETARIA.DE.INFRAESTRUTURA', 'SECRETARIA.DE.MEIO.AMBIENTE.E.SUSTENTABILIDADE', 'SECRETARIA.DE.MOBILIDADE.E.CONTROLE.URBANO', 'SECRETARIA.DE.PLANEJAMENTO.E.GESTAO', 'SECRETARIA.DE.PLANEJAMENTO.URBANO', 'SECRETARIA.DE.SANEAMENTO', 'SECRETARIA.DE.SAUDE', 'SECRETARIA.DE.SEGURANCA.CIDADA', 'SECRETARIA.DE.TRABALHO.QUALIFICACAO.E.EMPREENDEDORISMO', 'SECRETARIA.DE.TURISMO.E.LAZER', 'SECRETARIA.MULHER')

acessoInformacao_2 <- acm.disjonctif(as.data.frame(acessoInformacao$informacoes_pessoais))
names(acessoInformacao_2) <- c('COM.INFO.PESSOAL', 'SEM.INFO.PESSOAL')

acessoInformacao_3 <- acm.disjonctif(as.data.frame(acessoInformacao$situacao_pedido))
names(acessoInformacao_3) <- c('INDEFERIDO', 'RESPONDIDO')

acessoInformacao_4 <- acm.disjonctif(as.data.frame(acessoInformacao$motivo_pedido))
names(acessoInformacao_4) <- c('ESTUDO', 'MOTIVO.NAO.INFORMADO', 'OUTROS.MOTIVOS', 'PESQUISA')

acessoInformacao_5 <- acm.disjonctif(as.data.frame(acessoInformacao$sexo_solicitante))
names(acessoInformacao_5) <- c('SEXO.NAO.INFORMADO', 'FEMININO', 'MASCULINO')

acessoInformacao_6 <- acm.disjonctif(as.data.frame(acessoInformacao$escolaridade_solicitante))
names(acessoInformacao_6) <- c('ENSINO.FUNDAMENTAL', 'ENSINO.MEDIO', 'ENSINO.SUPERIOR', 'MESTRADO.DOUTORADO', 'NAO.INFORMADO', 'OUTRA.ESCOLARIDADE', 'POS.GRADUACAO', 'SEM.INSTRUCAO.FORMAL')

acessoInformacao_7 <- acm.disjonctif(as.data.frame(acessoInformacao$cidade_solicitante))
names(acessoInformacao_7) <- c('OUTRA', 'RECIFE')

acessoInformacao_8 <- acm.disjonctif(as.data.frame(acessoInformacao$profissao_solicitante))
names(acessoInformacao_8) <- c('EMPREGADO.SETOR.PRIVADO', 'EMPRESARIO.EMPREENDEDOR', 'ESTUDANTE', 'JORNALISTA', 'MEMBRO.DE.ONG.INTERNACIONAL', 'MEMBRO.DE.ONG.NACIONAL', 'PROFISSAO.NAO.INFORMADA', 'OUTRA.PROFISSAO', 'PESQUISADOR', 'PROFESSOR', 'PROFISSIONAL.AUTONOMO', 'PROFISSIONAL.LIBERAL', 'SERVIDOR.PUBLICO.ESTADUAL', 'SERVIDOR.PUBLICO.FEDERAL', 'SERVIDOR.PUBLICO.MUNICIPAL')

acessoInformacao <- cbind(acessoInformacao, acessoInformacao_1)
acessoInformacao <- cbind(acessoInformacao, acessoInformacao_2)
acessoInformacao <- cbind(acessoInformacao, acessoInformacao_3)
acessoInformacao <- cbind(acessoInformacao, acessoInformacao_4)
acessoInformacao <- cbind(acessoInformacao, acessoInformacao_5)
acessoInformacao <- cbind(acessoInformacao, acessoInformacao_6)
acessoInformacao <- cbind(acessoInformacao, acessoInformacao_7)
acessoInformacao <- cbind(acessoInformacao, acessoInformacao_8)

# transformando factors
  #acessoInformacao$informacoes_pessoais <- as.factor(acessoInformacao$informacoes_pessoais)
  #acessoInformacao$situacao_pedido <- as.factor(acessoInformacao$situacao_pedido)
  #acessoInformacao$orgao_solicitacao <- as.factor(acessoInformacao$orgao_solicitacao)
  #acessoInformacao$motivo_pedido <- as.factor(acessoInformacao$motivo_pedido)
  #acessoInformacao$sexo_solicitante <- as.factor(acessoInformacao$sexo_solicitante)
  #acessoInformacao$escolaridade_solicitante <- as.factor(acessoInformacao$escolaridade_solicitante)
  #acessoInformacao$profissao_solicitante <- as.factor(acessoInformacao$profissao_solicitante)
  #acessoInformacao$cidade_solicitante <- as.factor(acessoInformacao$cidade_solicitante)


# Treino e Teste: Pré-processamento
particaoInfo = createDataPartition(acessoInformacao$dias, p=.7, list = F) # cria a partição 70-30
treinoInfo = acessoInformacao[particaoInfo, ] # treino
testeInfo = acessoInformacao[-particaoInfo, ] # - treino = teste

# Validação Cruzada: Pré-processamento
# Controle de treinamento
train.control <- trainControl(method = "cv", number = 10, verboseIter = T) # controle de treino

# Treinamentos
## Regressão Linear
INFO_LM <- train(dias ~ ENSINO.FUNDAMENTAL + ENSINO.MEDIO + ENSINO.SUPERIOR +  MESTRADO.DOUTORADO + NAO.INFORMADO + OUTRA.ESCOLARIDADE + POS.GRADUACAO + SEM.INSTRUCAO.FORMAL + COM.INFO.PESSOAL + SEM.INFO.PESSOAL + ESTUDO + MOTIVO.NAO.INFORMADO + OUTROS.MOTIVOS + PESQUISA + EMPREGADO.SETOR.PRIVADO + EMPRESARIO.EMPREENDEDOR + ESTUDANTE + JORNALISTA + MEMBRO.DE.ONG.INTERNACIONAL + MEMBRO.DE.ONG.NACIONAL + PROFISSAO.NAO.INFORMADA + OUTRA.PROFISSAO + PESQUISADOR + PROFESSOR + PROFISSIONAL.AUTONOMO + PROFISSIONAL.LIBERAL + SERVIDOR.PUBLICO.ESTADUAL + SERVIDOR.PUBLICO.FEDERAL + SERVIDOR.PUBLICO.MUNICIPAL + ASSESSORIA.ESPECIAL + AUTARQUIA.DE.MANUTENCAO.E.LIMPEZA.URBANA + AUTARQUIA.DE.SERVICOS.URBANOS.DO.RECIFE + AUTARQUIA.DE.TRANSITO.E.TRANSPORTE.URBANO.DO.RECIFE + AUTARQUIA.DE.URBANIZACAO.DO.RECIFE + AUTARQUIA.MUNICIPAL.DE.PREVID.E.ASSISTÊNCIA.A.SAUDE.SERVIDORES + CONTROLADORIA.GERAL.DO.MUNICIPIO + EMPRESA.MUNICIPAL.DE.INFORMATICA + FUNDACAO.DE.CULTURA.DA.CIDADE.DO.RECIFE + GABINETE.DE.IMPRENSA + GABINETE.DE.PROJETOS.ESPECIAIS + GABINETE.DE.REPRESENTACAO.EM.BRASILIA.E.RELACOES.INTERNACIONAIS + GABINETE.DO.PREFEITO + PROCURADORIA.GERAL.DO.MUNICIPIO + SEC.DE.DESENV.SOCIAL.JUVENTUDE.POLIT.SOBRE.DROGA.E.DIR.HUMANOS + SECRETARIA.DE.ADMINISTRAÇÃO.E.GESTAO.DE.PESSOAS + SECRETARIA.DE.CULTURA + SECRETARIA.DE.DESENV.ECONÔMICO.CIÊNCIA.TECNOLOGIA.E.INOVAÇÃO + SECRETARIA.DE.EDUCACAO + SECRETARIA.DE.FINANCAS + SECRETARIA.DE.GOVERNO.E.PARTICIPACAO.SOCIAL + SECRETARIA.DE.INFRAESTRUTURA + SECRETARIA.DE.MEIO.AMBIENTE.E.SUSTENTABILIDADE + SECRETARIA.DE.MOBILIDADE.E.CONTROLE.URBANO + SECRETARIA.DE.PLANEJAMENTO.E.GESTAO + SECRETARIA.DE.PLANEJAMENTO.URBANO + SECRETARIA.DE.SANEAMENTO + SECRETARIA.DE.SAUDE + SECRETARIA.DE.SEGURANCA.CIDADA + SECRETARIA.DE.TRABALHO.QUALIFICACAO.E.EMPREENDEDORISMO + SECRETARIA.DE.TURISMO.E.LAZER + SECRETARIA.MULHER + INDEFERIDO + RESPONDIDO, data = treinoInfo, method = "lm", trControl = train.control)
summary(INFO_LM) # sumário do modelo linear
plot(varImp(INFO_LM))

## Árvore de Decisão
INFO_RPART <- train(dias ~ ENSINO.FUNDAMENTAL + ENSINO.MEDIO + ENSINO.SUPERIOR +  MESTRADO.DOUTORADO + NAO.INFORMADO + OUTRA.ESCOLARIDADE + POS.GRADUACAO + SEM.INSTRUCAO.FORMAL + COM.INFO.PESSOAL + SEM.INFO.PESSOAL + ESTUDO + MOTIVO.NAO.INFORMADO + OUTROS.MOTIVOS + PESQUISA + EMPREGADO.SETOR.PRIVADO + EMPRESARIO.EMPREENDEDOR + ESTUDANTE + JORNALISTA + MEMBRO.DE.ONG.INTERNACIONAL + MEMBRO.DE.ONG.NACIONAL + PROFISSAO.NAO.INFORMADA + OUTRA.PROFISSAO + PESQUISADOR + PROFESSOR + PROFISSIONAL.AUTONOMO + PROFISSIONAL.LIBERAL + SERVIDOR.PUBLICO.ESTADUAL + SERVIDOR.PUBLICO.FEDERAL + SERVIDOR.PUBLICO.MUNICIPAL + ASSESSORIA.ESPECIAL + AUTARQUIA.DE.MANUTENCAO.E.LIMPEZA.URBANA + AUTARQUIA.DE.SERVICOS.URBANOS.DO.RECIFE + AUTARQUIA.DE.TRANSITO.E.TRANSPORTE.URBANO.DO.RECIFE + AUTARQUIA.DE.URBANIZACAO.DO.RECIFE + AUTARQUIA.MUNICIPAL.DE.PREVID.E.ASSISTÊNCIA.A.SAUDE.SERVIDORES + CONTROLADORIA.GERAL.DO.MUNICIPIO + EMPRESA.MUNICIPAL.DE.INFORMATICA + FUNDACAO.DE.CULTURA.DA.CIDADE.DO.RECIFE + GABINETE.DE.IMPRENSA + GABINETE.DE.PROJETOS.ESPECIAIS + GABINETE.DE.REPRESENTACAO.EM.BRASILIA.E.RELACOES.INTERNACIONAIS + GABINETE.DO.PREFEITO + PROCURADORIA.GERAL.DO.MUNICIPIO + SEC.DE.DESENV.SOCIAL.JUVENTUDE.POLIT.SOBRE.DROGA.E.DIR.HUMANOS + SECRETARIA.DE.ADMINISTRAÇÃO.E.GESTAO.DE.PESSOAS + SECRETARIA.DE.CULTURA + SECRETARIA.DE.DESENV.ECONÔMICO.CIÊNCIA.TECNOLOGIA.E.INOVAÇÃO + SECRETARIA.DE.EDUCACAO + SECRETARIA.DE.FINANCAS + SECRETARIA.DE.GOVERNO.E.PARTICIPACAO.SOCIAL + SECRETARIA.DE.INFRAESTRUTURA + SECRETARIA.DE.MEIO.AMBIENTE.E.SUSTENTABILIDADE + SECRETARIA.DE.MOBILIDADE.E.CONTROLE.URBANO + SECRETARIA.DE.PLANEJAMENTO.E.GESTAO + SECRETARIA.DE.PLANEJAMENTO.URBANO + SECRETARIA.DE.SANEAMENTO + SECRETARIA.DE.SAUDE + SECRETARIA.DE.SEGURANCA.CIDADA + SECRETARIA.DE.TRABALHO.QUALIFICACAO.E.EMPREENDEDORISMO + SECRETARIA.DE.TURISMO.E.LAZER + SECRETARIA.MULHER + INDEFERIDO + RESPONDIDO, data = treinoInfo, method = "rpart", trControl = train.control)

summary(INFO_RPART)
fancyRpartPlot(INFO_RPART$finalModel) # desenho da árvore
plot(varImp(INFO_RPART)) # importância das variáveis

# Bagging com Floresta Aleatória
INFO_RF <- train(dias ~ ENSINO.FUNDAMENTAL + ENSINO.MEDIO + ENSINO.SUPERIOR +  MESTRADO.DOUTORADO + NAO.INFORMADO + OUTRA.ESCOLARIDADE + POS.GRADUACAO + SEM.INSTRUCAO.FORMAL + COM.INFO.PESSOAL + SEM.INFO.PESSOAL + ESTUDO + MOTIVO.NAO.INFORMADO + OUTROS.MOTIVOS + PESQUISA + EMPREGADO.SETOR.PRIVADO + EMPRESARIO.EMPREENDEDOR + ESTUDANTE + JORNALISTA + MEMBRO.DE.ONG.INTERNACIONAL + MEMBRO.DE.ONG.NACIONAL + PROFISSAO.NAO.INFORMADA + OUTRA.PROFISSAO + PESQUISADOR + PROFESSOR + PROFISSIONAL.AUTONOMO + PROFISSIONAL.LIBERAL + SERVIDOR.PUBLICO.ESTADUAL + SERVIDOR.PUBLICO.FEDERAL + SERVIDOR.PUBLICO.MUNICIPAL + ASSESSORIA.ESPECIAL + AUTARQUIA.DE.MANUTENCAO.E.LIMPEZA.URBANA + AUTARQUIA.DE.SERVICOS.URBANOS.DO.RECIFE + AUTARQUIA.DE.TRANSITO.E.TRANSPORTE.URBANO.DO.RECIFE + AUTARQUIA.DE.URBANIZACAO.DO.RECIFE + AUTARQUIA.MUNICIPAL.DE.PREVID.E.ASSISTÊNCIA.A.SAUDE.SERVIDORES + CONTROLADORIA.GERAL.DO.MUNICIPIO + EMPRESA.MUNICIPAL.DE.INFORMATICA + FUNDACAO.DE.CULTURA.DA.CIDADE.DO.RECIFE + GABINETE.DE.IMPRENSA + GABINETE.DE.PROJETOS.ESPECIAIS + GABINETE.DE.REPRESENTACAO.EM.BRASILIA.E.RELACOES.INTERNACIONAIS + GABINETE.DO.PREFEITO + PROCURADORIA.GERAL.DO.MUNICIPIO + SEC.DE.DESENV.SOCIAL.JUVENTUDE.POLIT.SOBRE.DROGA.E.DIR.HUMANOS + SECRETARIA.DE.ADMINISTRAÇÃO.E.GESTAO.DE.PESSOAS + SECRETARIA.DE.CULTURA + SECRETARIA.DE.DESENV.ECONÔMICO.CIÊNCIA.TECNOLOGIA.E.INOVAÇÃO + SECRETARIA.DE.EDUCACAO + SECRETARIA.DE.FINANCAS + SECRETARIA.DE.GOVERNO.E.PARTICIPACAO.SOCIAL + SECRETARIA.DE.INFRAESTRUTURA + SECRETARIA.DE.MEIO.AMBIENTE.E.SUSTENTABILIDADE + SECRETARIA.DE.MOBILIDADE.E.CONTROLE.URBANO + SECRETARIA.DE.PLANEJAMENTO.E.GESTAO + SECRETARIA.DE.PLANEJAMENTO.URBANO + SECRETARIA.DE.SANEAMENTO + SECRETARIA.DE.SAUDE + SECRETARIA.DE.SEGURANCA.CIDADA + SECRETARIA.DE.TRABALHO.QUALIFICACAO.E.EMPREENDEDORISMO + SECRETARIA.DE.TURISMO.E.LAZER + SECRETARIA.MULHER + INDEFERIDO + RESPONDIDO, data = treinoInfo, method = "cforest", trControl = train.control)

plot(INFO_RF) # evolução do modelo
plot(varImp(INFO_RF)) # plot de importância

# Boosting com Boosted Generalized Linear Model
INFO_ADA <- train(dias ~ ENSINO.FUNDAMENTAL + ENSINO.MEDIO + ENSINO.SUPERIOR +  MESTRADO.DOUTORADO + NAO.INFORMADO + OUTRA.ESCOLARIDADE + POS.GRADUACAO + SEM.INSTRUCAO.FORMAL + COM.INFO.PESSOAL + SEM.INFO.PESSOAL + ESTUDO + MOTIVO.NAO.INFORMADO + OUTROS.MOTIVOS + PESQUISA + EMPREGADO.SETOR.PRIVADO + EMPRESARIO.EMPREENDEDOR + ESTUDANTE + JORNALISTA + MEMBRO.DE.ONG.INTERNACIONAL + MEMBRO.DE.ONG.NACIONAL + PROFISSAO.NAO.INFORMADA + OUTRA.PROFISSAO + PESQUISADOR + PROFESSOR + PROFISSIONAL.AUTONOMO + PROFISSIONAL.LIBERAL + SERVIDOR.PUBLICO.ESTADUAL + SERVIDOR.PUBLICO.FEDERAL + SERVIDOR.PUBLICO.MUNICIPAL + ASSESSORIA.ESPECIAL + AUTARQUIA.DE.MANUTENCAO.E.LIMPEZA.URBANA + AUTARQUIA.DE.SERVICOS.URBANOS.DO.RECIFE + AUTARQUIA.DE.TRANSITO.E.TRANSPORTE.URBANO.DO.RECIFE + AUTARQUIA.DE.URBANIZACAO.DO.RECIFE + AUTARQUIA.MUNICIPAL.DE.PREVID.E.ASSISTÊNCIA.A.SAUDE.SERVIDORES + CONTROLADORIA.GERAL.DO.MUNICIPIO + EMPRESA.MUNICIPAL.DE.INFORMATICA + FUNDACAO.DE.CULTURA.DA.CIDADE.DO.RECIFE + GABINETE.DE.IMPRENSA + GABINETE.DE.PROJETOS.ESPECIAIS + GABINETE.DE.REPRESENTACAO.EM.BRASILIA.E.RELACOES.INTERNACIONAIS + GABINETE.DO.PREFEITO + PROCURADORIA.GERAL.DO.MUNICIPIO + SEC.DE.DESENV.SOCIAL.JUVENTUDE.POLIT.SOBRE.DROGA.E.DIR.HUMANOS + SECRETARIA.DE.ADMINISTRAÇÃO.E.GESTAO.DE.PESSOAS + SECRETARIA.DE.CULTURA + SECRETARIA.DE.DESENV.ECONÔMICO.CIÊNCIA.TECNOLOGIA.E.INOVAÇÃO + SECRETARIA.DE.EDUCACAO + SECRETARIA.DE.FINANCAS + SECRETARIA.DE.GOVERNO.E.PARTICIPACAO.SOCIAL + SECRETARIA.DE.INFRAESTRUTURA + SECRETARIA.DE.MEIO.AMBIENTE.E.SUSTENTABILIDADE + SECRETARIA.DE.MOBILIDADE.E.CONTROLE.URBANO + SECRETARIA.DE.PLANEJAMENTO.E.GESTAO + SECRETARIA.DE.PLANEJAMENTO.URBANO + SECRETARIA.DE.SANEAMENTO + SECRETARIA.DE.SAUDE + SECRETARIA.DE.SEGURANCA.CIDADA + SECRETARIA.DE.TRABALHO.QUALIFICACAO.E.EMPREENDEDORISMO + SECRETARIA.DE.TURISMO.E.LAZER + SECRETARIA.MULHER + INDEFERIDO + RESPONDIDO, data = treinoInfo, method = "glmboost", trControl = train.control)

plot(INFO_ADA) # evolução do modelo
print(INFO_ADA) # modelo
summary(INFO_ADA) # sumário

melhor_modelo <- resamples(list(LM = INFO_LM, RPART = INFO_RPART, RF = INFO_RF, ADABOOST = INFO_ADA))
melhor_modelo

summary(melhor_modelo)

predVals <- extractPrediction(list(INFO_RF), testX = testeInfo[, c(15:55, 59:83)], testY = testeInfo$dias) 

plotObsVsPred(predVals)
